name: Generate Android Artifacts

on:
  workflow_dispatch: # Permite a execução manual
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore Solution
        run: dotnet restore scan-my-bill.slnx

      - name: Install MAUI Workload
        run: dotnet workload install maui-android

      - name: Run Unit Tests
        run: dotnet test scan-my-bill.slnx --no-build -c Release --verbosity normal

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" > keystore_base64.txt
          certutil -decode keystore_base64.txt release.keystore

      # Gera o .AAB (Para a Google Play)
      - name: Build AAB
        run: |
          dotnet publish -f net10.0-android -c Release `
          -p:AndroidKeyStore=true `
          -p:AndroidSigningKeyStore=release.keystore `
          -p:AndroidSigningKeyAlias=${{ secrets.KEY_ALIAS }} `
          -p:AndroidSigningKeyPass=${{ secrets.KEY_PASSWORD }} `
          -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }}

      # Gera o .APK (Para instalação direta/testes)
      - name: Build APK
        run: |
          dotnet publish -f net10.0-android -c Release -p:AndroidPackageFormat=apk `
          -p:AndroidKeyStore=true `
          -p:AndroidSigningKeyStore=release.keystore `
          -p:AndroidSigningKeyAlias=${{ secrets.KEY_ALIAS }} `
          -p:AndroidSigningKeyPass=${{ secrets.KEY_PASSWORD }} `
          -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }}

      # Cria a Release no GitHub e anexa os arquivos automaticamente
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/*-Signed.aab
            **/*-Signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}